void main(List<String> args) {
  Future((){
    throw Exception('Hubo un error');
  }).then((_){
    print("Ã‰xito!!");
  }).catchError((error){
    print('Error: $error');
  });
}